# VNPAY CONFIG M?I
vnpay.tmnCode=69Q2HQNA
vnpay.hashSecret=UM4C1WQLUZS01BNI9I4BBY3N40CPEH1K
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/api/payment/vnpay-return

# C?U HÌNH G?I EMAIL OTP HI?N T?I C?A S?P
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=animefighterssimulator2906@gmail.com
spring.mail.password=gbynmqbflvwlkhet
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ? THÊM 3 DÒNG NÀY VÀO D??I CÙNG ?? T?NG TH?I GIAN CH? LÊN 15 GIÂY (15000ms)
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000

# Ép API tr? v? gi? Vi?t Nam
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss